import type { Consonant } from "../types";

export const consonants: Record<string, Consonant> = {
  giyeok: {
    kind: "consonant",
    char: "ㄱ",
    romanization: "g/k",
    ipa: "/k/",
    mnemonicHook: "gun",
    mnemonicShape: "Looks like the corner of a gun barrel pointing down and to the right.",
    articulation: "Back of the tongue touches the soft palate, then releases. Like the g in go.",
    soundsLike: { word: "go", phonetic: "g" },
    audioHint: "기역",
    soundHint: "가",
  },
  nieun: {
    kind: "consonant",
    char: "ㄴ",
    romanization: "n",
    ipa: "/n/",
    mnemonicHook: "nose",
    mnemonicShape: "Looks like an L. The tongue presses where the L's corner is.",
    articulation: "Tip of the tongue presses behind the upper teeth. Like the n in no.",
    soundsLike: { word: "no", phonetic: "n" },
    audioHint: "니은",
    soundHint: "나",
  },
  digeut: {
    kind: "consonant",
    char: "ㄷ",
    romanization: "d/t",
    ipa: "/t/",
    mnemonicHook: "door",
    mnemonicShape: "Like ㄴ with a roof. A door frame, opening to the right.",
    articulation: "Tongue tip taps behind the upper teeth, then releases. Like the d in door.",
    soundsLike: { word: "door", phonetic: "d" },
    audioHint: "디귿",
    soundHint: "다",
  },
  rieul: {
    kind: "consonant",
    char: "ㄹ",
    romanization: "r/l",
    ipa: "/ɾ/",
    mnemonicHook: "ribbon",
    mnemonicShape: "A bending ribbon, twisting back on itself.",
    articulation: "Tongue taps the ridge behind the teeth quickly. Somewhere between an English r and l.",
    soundsLike: { word: "ribbon", phonetic: "r/l" },
    audioHint: "리을",
    soundHint: "라",
  },
  mieum: {
    kind: "consonant",
    char: "ㅁ",
    romanization: "m",
    ipa: "/m/",
    mnemonicHook: "mouth",
    mnemonicShape: "A closed box, like lips pressed together to make the m sound.",
    articulation: "Lips press together gently, sound comes through the nose. Like the m in me.",
    soundsLike: { word: "me", phonetic: "m" },
    audioHint: "미음",
    soundHint: "마",
  },
  bieup: {
    kind: "consonant",
    char: "ㅂ",
    romanization: "b/p",
    ipa: "/p/",
    mnemonicHook: "bucket",
    mnemonicShape: "A bucket with the opening at the top. Holds the b sound inside.",
    articulation: "Lips press together, then release with a small puff. Like the b in boy.",
    soundsLike: { word: "boy", phonetic: "b" },
    audioHint: "비읍",
    soundHint: "바",
  },
  siot: {
    kind: "consonant",
    char: "ㅅ",
    romanization: "s",
    ipa: "/s/",
    mnemonicHook: "sitting",
    mnemonicShape: "Two legs sitting down, slightly bent. The air hisses out between them.",
    articulation: "Tongue near the roof of the mouth, air hisses through. Like the s in sun.",
    soundsLike: { word: "sun", phonetic: "s" },
    audioHint: "시옷",
    soundHint: "사",
  },
  ieung: {
    kind: "consonant",
    char: "ㅇ",
    romanization: "(silent) / ng",
    ipa: "/ŋ/",
    mnemonicHook: "empty circle",
    mnemonicShape: "A simple circle. Silent at the start of a syllable, ng at the end.",
    articulation: "At the start of a syllable, no sound at all. At the end, like the ng in song.",
    soundsLike: { word: "song", phonetic: "ng" },
    audioHint: "이응",
    soundHint: "응",
  },
  jieut: {
    kind: "consonant",
    char: "ㅈ",
    romanization: "j",
    ipa: "/tɕ/",
    mnemonicHook: "jump",
    mnemonicShape: "Like ㅅ with a roof. Two legs jumping under shelter.",
    articulation: "Tongue presses the roof of the mouth, releases with a soft j sound. Like the j in joy.",
    soundsLike: { word: "joy", phonetic: "j" },
    audioHint: "지읒",
    soundHint: "자",
  },
  chieut: {
    kind: "consonant",
    char: "ㅊ",
    romanization: "ch",
    ipa: "/tɕʰ/",
    mnemonicHook: "chair",
    mnemonicShape: "ㅈ with an extra stroke on top. The stroke is the puff of air.",
    articulation: "Same as ㅈ but with a stronger puff of breath. Like the ch in chair.",
    soundsLike: { word: "chair", phonetic: "ch" },
    audioHint: "치읓",
    soundHint: "차",
  },
  kieuk: {
    kind: "consonant",
    char: "ㅋ",
    romanization: "k",
    ipa: "/kʰ/",
    mnemonicHook: "key",
    mnemonicShape: "ㄱ with an extra stroke inside. The stroke is the puff of air.",
    articulation: "Same as ㄱ but with a stronger puff of breath. Like the k in key.",
    soundsLike: { word: "key", phonetic: "k" },
    audioHint: "키읔",
    soundHint: "카",
  },
  tieut: {
    kind: "consonant",
    char: "ㅌ",
    romanization: "t",
    ipa: "/tʰ/",
    mnemonicHook: "tea",
    mnemonicShape: "ㄷ with an extra stroke inside. The stroke is the puff of air.",
    articulation: "Same as ㄷ but with a stronger puff of breath. Like the t in tea.",
    soundsLike: { word: "tea", phonetic: "t" },
    audioHint: "티읕",
    soundHint: "타",
  },
  pieup: {
    kind: "consonant",
    char: "ㅍ",
    romanization: "p",
    ipa: "/pʰ/",
    mnemonicHook: "pi",
    mnemonicShape: "Like the Greek letter pi (π). Two pillars holding up a roof.",
    articulation: "Same as ㅂ but with a stronger puff of breath. Like the p in pie.",
    soundsLike: { word: "pie", phonetic: "p" },
    audioHint: "피읖",
    soundHint: "파",
  },
  hieut: {
    kind: "consonant",
    char: "ㅎ",
    romanization: "h",
    ipa: "/h/",
    mnemonicHook: "hat",
    mnemonicShape: "ㅇ with a hat. The hat is what releases the h sound.",
    articulation: "A soft breath out from the throat. Like the h in hat.",
    soundsLike: { word: "hat", phonetic: "h" },
    audioHint: "히읗",
    soundHint: "하",
  },
};
