import type { Lesson } from "../types";
import { consonants } from "./consonants";
import { vowels } from "./vowels";

const FIRST_RECALL_NOTE =
  "Now we test what stuck. You will see a letter and pick the sound it makes. If you miss one, it will come back later in this lesson so you can try again. No pressure.";

const FIRST_PRODUCE_NOTE =
  "Last test of the lesson. No more options to pick from. Just type the sound the letter makes. Typing it out makes the memory stick deeper than picking from a list.";

export const sixBasicVowels: Lesson = {
  id: "m1-l1",
  slug: "six-basic-vowels",
  number: 1,
  title: "The six basic vowels",
  blurb: "ㅏ ㅓ ㅗ ㅜ ㅡ ㅣ. The foundation of every Korean syllable.",
  introduces: [vowels.a, vowels.eo, vowels.o, vowels.u, vowels.eu, vowels.i],
  estimatedMinutes: 14,
  exercises: [
    { id: "m1-l1-e1", type: "meet", prompt: "Meet ㅏ. Sound, shape, and how to make it.", target: vowels.a, estimatedSeconds: 25 },
    { id: "m1-l1-e2", type: "meet", prompt: "Meet ㅓ. The mirror of ㅏ.", target: vowels.eo, estimatedSeconds: 25 },
    { id: "m1-l1-e3", type: "meet", prompt: "Meet ㅗ. Now the line points up.", target: vowels.o, estimatedSeconds: 25 },
    { id: "m1-l1-e4", type: "meet", prompt: "Meet ㅜ. The mirror of ㅗ.", target: vowels.u, estimatedSeconds: 25 },
    { id: "m1-l1-e5", type: "meet", prompt: "Meet ㅡ. Just a flat line.", target: vowels.eu, estimatedSeconds: 20 },
    { id: "m1-l1-e6", type: "meet", prompt: "Meet ㅣ. The simplest vowel of all.", target: vowels.i, estimatedSeconds: 20 },
    { id: "m1-l1-e7", type: "recall", prompt: "What sound does this letter make?", target: vowels.a, options: [vowels.a, vowels.eo], estimatedSeconds: 15, note: FIRST_RECALL_NOTE },
    { id: "m1-l1-e8", type: "recall", prompt: "What sound does this letter make?", target: vowels.o, options: [vowels.o, vowels.u], estimatedSeconds: 15 },
    { id: "m1-l1-e9", type: "recall", prompt: "What sound does this letter make?", target: vowels.eu, options: [vowels.eu, vowels.i], estimatedSeconds: 15 },
    { id: "m1-l1-e10", type: "recognize", prompt: "Which letter makes this sound?", target: vowels.eo, options: [vowels.a, vowels.eo, vowels.o, vowels.u, vowels.eu, vowels.i], estimatedSeconds: 20 },
    { id: "m1-l1-e11", type: "recognize", prompt: "Which letter makes this sound?", target: vowels.u, options: [vowels.a, vowels.eo, vowels.o, vowels.u, vowels.eu, vowels.i], estimatedSeconds: 20 },
    { id: "m1-l1-e12", type: "recognize", prompt: "Which letter makes this sound?", target: vowels.i, options: [vowels.a, vowels.eo, vowels.o, vowels.u, vowels.eu, vowels.i], estimatedSeconds: 20 },
    { id: "m1-l1-e13", type: "produce", prompt: "Type the sound this letter makes.", target: vowels.a, estimatedSeconds: 25, note: FIRST_PRODUCE_NOTE },
    { id: "m1-l1-e14", type: "produce", prompt: "Type the sound this letter makes.", target: vowels.o, estimatedSeconds: 20 },
    { id: "m1-l1-e15", type: "produce", prompt: "Type the sound this letter makes.", target: vowels.eu, estimatedSeconds: 20 },
  ],
};

export const yVowels: Lesson = {
  id: "m1-l2",
  slug: "y-vowels",
  number: 2,
  title: "The y-vowels",
  blurb: "ㅑ ㅕ ㅛ ㅠ. Add a dash, add a y sound.",
  introduces: [vowels.ya, vowels.yeo, vowels.yo, vowels.yu],
  estimatedMinutes: 11,
  exercises: [
    {
      id: "m1-l2-e1",
      type: "meet",
      prompt: "Meet ㅑ. ㅏ with one extra dash.",
      target: vowels.ya,
      estimatedSeconds: 25,
      note: "Korean has a clever pattern. Add an extra dash to any basic vowel and you get its y-version. ㅏ becomes ㅑ. ㅓ becomes ㅕ. Same direction, just doubled. The extra dash means the sound starts with a y.",
    },
    { id: "m1-l2-e2", type: "meet", prompt: "Meet ㅕ. ㅓ with one extra dash.", target: vowels.yeo, estimatedSeconds: 20 },
    { id: "m1-l2-e3", type: "meet", prompt: "Meet ㅛ. ㅗ with one extra dash.", target: vowels.yo, estimatedSeconds: 20 },
    { id: "m1-l2-e4", type: "meet", prompt: "Meet ㅠ. ㅜ with one extra dash.", target: vowels.yu, estimatedSeconds: 20 },
    { id: "m1-l2-e5", type: "recall", prompt: "What sound does this letter make?", target: vowels.ya, options: [vowels.ya, vowels.yeo], estimatedSeconds: 15, note: FIRST_RECALL_NOTE },
    { id: "m1-l2-e6", type: "recall", prompt: "What sound does this letter make?", target: vowels.yo, options: [vowels.yo, vowels.yu], estimatedSeconds: 15 },
    { id: "m1-l2-e7", type: "recognize", prompt: "Which letter makes this sound?", target: vowels.yeo, options: [vowels.ya, vowels.yeo, vowels.yo, vowels.yu], estimatedSeconds: 20 },
    { id: "m1-l2-e8", type: "recognize", prompt: "Which letter makes this sound?", target: vowels.yu, options: [vowels.ya, vowels.yeo, vowels.yo, vowels.yu], estimatedSeconds: 20 },
    { id: "m1-l2-e9", type: "produce", prompt: "Type the sound this letter makes.", target: vowels.ya, estimatedSeconds: 25, note: FIRST_PRODUCE_NOTE },
    { id: "m1-l2-e10", type: "produce", prompt: "Type the sound this letter makes.", target: vowels.yo, estimatedSeconds: 20 },
  ],
};

export const firstFourConsonants: Lesson = {
  id: "m1-l3",
  slug: "first-four-consonants",
  number: 3,
  title: "First four consonants",
  blurb: "ㄱ ㄴ ㅁ ㅅ. Now that you know the vowels, the consonants click into place.",
  introduces: [consonants.giyeok, consonants.nieun, consonants.mieum, consonants.siot],
  estimatedMinutes: 12,
  exercises: [
    {
      id: "m1-l3-e1",
      type: "meet",
      prompt: "Meet ㄱ. You will hear it as 가.",
      target: consonants.giyeok,
      estimatedSeconds: 25,
      note: "Korean consonants do not stand alone in speech. To hear ㄱ you pair it with a vowel: ㄱ + ㅏ = 가. That is why we learned the vowels first. The consonant is the start of the sound, not the whole sound.",
    },
    { id: "m1-l3-e2", type: "meet", prompt: "Meet ㄴ. You will hear it as 나.", target: consonants.nieun, estimatedSeconds: 20 },
    { id: "m1-l3-e3", type: "meet", prompt: "Meet ㅁ. Hear it as 마.", target: consonants.mieum, estimatedSeconds: 20 },
    { id: "m1-l3-e4", type: "meet", prompt: "Meet ㅅ. Hear it as 사.", target: consonants.siot, estimatedSeconds: 20 },
    { id: "m1-l3-e5", type: "recall", prompt: "What sound does this letter make?", target: consonants.giyeok, options: [consonants.giyeok, consonants.nieun], estimatedSeconds: 15, note: FIRST_RECALL_NOTE },
    { id: "m1-l3-e6", type: "recall", prompt: "What sound does this letter make?", target: consonants.mieum, options: [consonants.mieum, consonants.siot], estimatedSeconds: 15 },
    { id: "m1-l3-e7", type: "recognize", prompt: "Which letter makes this sound?", target: consonants.nieun, options: [consonants.giyeok, consonants.nieun, consonants.mieum, consonants.siot], estimatedSeconds: 20 },
    { id: "m1-l3-e8", type: "recognize", prompt: "Which letter makes this sound?", target: consonants.siot, options: [consonants.giyeok, consonants.nieun, consonants.mieum, consonants.siot], estimatedSeconds: 20 },
    { id: "m1-l3-e9", type: "produce", prompt: "Type the sound this letter makes.", target: consonants.giyeok, estimatedSeconds: 25, note: FIRST_PRODUCE_NOTE },
    { id: "m1-l3-e10", type: "produce", prompt: "Type the sound this letter makes.", target: consonants.mieum, estimatedSeconds: 20 },
  ],
};

export const buildFirstBlocks: Lesson = {
  id: "m1-l3b",
  slug: "build-your-first-blocks",
  number: 4,
  title: "Build your first blocks",
  blurb: "Snap a consonant and a vowel together into a real Korean syllable, the way Hangul is actually read.",
  introduces: [],
  estimatedMinutes: 3,
  exercises: [
    {
      id: "m1-l3b-e0",
      type: "intro",
      prompt: "How a syllable block works",
      note: "Every Korean syllable is a block: a consonant and a vowel fused into one square. Where the vowel sits depends on its shape. Tap a block to hear it.",
      target: "",
      estimatedSeconds: 20,
    },
    {
      id: "m1-l3b-e1",
      type: "build",
      prompt: "Build a syllable block",
      note: "Korean is not read letter by letter. It is read in blocks. Pick one consonant and one vowel and watch them snap into a single syllable. Notice where the vowel lands: some stand to the right, some tuck in underneath. A few of these blocks are real words: 나 means me, 소 means cow, 무 means radish.",
      target: "",
      options: [
        consonants.giyeok,
        consonants.nieun,
        consonants.mieum,
        consonants.siot,
        vowels.a,
        vowels.eo,
        vowels.o,
        vowels.u,
        vowels.eu,
        vowels.i,
      ],
      estimatedSeconds: 60,
    },
    {
      id: "m1-l3b-e2",
      type: "buildTest",
      prompt: "Build this sound",
      note: "You will see a sound, written like /na/. Recall which consonant and vowel make it, build the block, then check. Tap the sound to hear it.",
      target: "나",
      options: [
        consonants.giyeok,
        consonants.nieun,
        consonants.mieum,
        consonants.siot,
        vowels.a,
        vowels.eo,
        vowels.o,
        vowels.u,
      ],
      estimatedSeconds: 30,
    },
    {
      id: "m1-l3b-e3",
      type: "buildTest",
      prompt: "Build this sound",
      target: "소",
      options: [
        consonants.giyeok,
        consonants.nieun,
        consonants.mieum,
        consonants.siot,
        vowels.a,
        vowels.eo,
        vowels.o,
        vowels.u,
      ],
      estimatedSeconds: 30,
    },
  ],
};

export const fiveMoreConsonants: Lesson = {
  id: "m1-l4",
  slug: "five-more-consonants",
  number: 5,
  title: "Five more consonants",
  blurb: "ㄷ ㄹ ㅂ ㅇ ㅈ. Plus the silent circle that unlocks standalone vowels.",
  introduces: [consonants.digeut, consonants.rieul, consonants.bieup, consonants.ieung, consonants.jieut],
  estimatedMinutes: 13,
  exercises: [
    {
      id: "m1-l4-e1",
      type: "meet",
      prompt: "Meet ㄷ. Hear it as 다.",
      target: consonants.digeut,
      estimatedSeconds: 25,
    },
    { id: "m1-l4-e2", type: "meet", prompt: "Meet ㄹ. Hear it as 라.", target: consonants.rieul, estimatedSeconds: 25 },
    { id: "m1-l4-e3", type: "meet", prompt: "Meet ㅂ. Hear it as 바.", target: consonants.bieup, estimatedSeconds: 20 },
    {
      id: "m1-l4-e4",
      type: "meet",
      prompt: "Meet ㅇ. The shape-shifter.",
      target: consonants.ieung,
      estimatedSeconds: 25,
      note: "ㅇ is special. When it starts a syllable, it makes no sound at all. It is just a placeholder so vowels can stand alone. 아 is just ah. 오 is just oh. When ㅇ appears at the END of a syllable, it makes an ng sound, like song.",
    },
    { id: "m1-l4-e5", type: "meet", prompt: "Meet ㅈ. Hear it as 자.", target: consonants.jieut, estimatedSeconds: 20 },
    { id: "m1-l4-e6", type: "recall", prompt: "What sound does this letter make?", target: consonants.digeut, options: [consonants.digeut, consonants.bieup], estimatedSeconds: 15, note: FIRST_RECALL_NOTE },
    { id: "m1-l4-e7", type: "recall", prompt: "What sound does this letter make?", target: consonants.rieul, options: [consonants.rieul, consonants.jieut], estimatedSeconds: 15 },
    { id: "m1-l4-e8", type: "recall", prompt: "What sound does this letter make?", target: consonants.ieung, options: [consonants.ieung, consonants.digeut], estimatedSeconds: 15 },
    { id: "m1-l4-e9", type: "recognize", prompt: "Which letter makes this sound?", target: consonants.bieup, options: [consonants.digeut, consonants.rieul, consonants.bieup, consonants.ieung, consonants.jieut], estimatedSeconds: 20 },
    { id: "m1-l4-e10", type: "recognize", prompt: "Which letter makes this sound?", target: consonants.jieut, options: [consonants.digeut, consonants.rieul, consonants.bieup, consonants.ieung, consonants.jieut], estimatedSeconds: 20 },
    { id: "m1-l4-e11", type: "produce", prompt: "Type the sound this letter makes.", target: consonants.digeut, estimatedSeconds: 25, note: FIRST_PRODUCE_NOTE },
    { id: "m1-l4-e12", type: "produce", prompt: "Type the sound this letter makes.", target: consonants.rieul, estimatedSeconds: 20 },
    { id: "m1-l4-e13", type: "produce", prompt: "Type the sound this letter makes.", target: consonants.ieung, estimatedSeconds: 20 },
  ],
};

export const aspiratedConsonants: Lesson = {
  id: "m1-l5",
  slug: "add-a-stroke-add-a-breath",
  number: 6,
  title: "Add a stroke, add a breath",
  blurb: "ㅋ ㅌ ㅍ ㅊ ㅎ. The aspirated cousins of letters you already know.",
  introduces: [consonants.kieuk, consonants.tieut, consonants.pieup, consonants.chieut, consonants.hieut],
  estimatedMinutes: 13,
  exercises: [
    {
      id: "m1-l5-e1",
      type: "meet",
      prompt: "Meet ㅋ. ㄱ with an extra stroke.",
      target: consonants.kieuk,
      estimatedSeconds: 25,
      note: "Korean does this beautiful thing. Take a consonant you know. Add a stroke. That extra stroke means a strong puff of air. ㄱ becomes ㅋ. ㄷ becomes ㅌ. ㅂ becomes ㅍ. ㅈ becomes ㅊ. Same place in the mouth, just breathier. You already know these sounds. We are just learning the stroke.",
    },
    { id: "m1-l5-e2", type: "meet", prompt: "Meet ㅌ. ㄷ with an extra stroke.", target: consonants.tieut, estimatedSeconds: 20 },
    { id: "m1-l5-e3", type: "meet", prompt: "Meet ㅍ. The aspirated ㅂ.", target: consonants.pieup, estimatedSeconds: 20 },
    { id: "m1-l5-e4", type: "meet", prompt: "Meet ㅊ. ㅈ with an extra stroke.", target: consonants.chieut, estimatedSeconds: 20 },
    { id: "m1-l5-e5", type: "meet", prompt: "Meet ㅎ. The lone h.", target: consonants.hieut, estimatedSeconds: 20 },
    { id: "m1-l5-e6", type: "recall", prompt: "What sound does this letter make?", target: consonants.kieuk, options: [consonants.kieuk, consonants.tieut], estimatedSeconds: 15, note: FIRST_RECALL_NOTE },
    { id: "m1-l5-e7", type: "recall", prompt: "What sound does this letter make?", target: consonants.pieup, options: [consonants.pieup, consonants.chieut], estimatedSeconds: 15 },
    { id: "m1-l5-e8", type: "recall", prompt: "What sound does this letter make?", target: consonants.hieut, options: [consonants.hieut, consonants.kieuk], estimatedSeconds: 15 },
    { id: "m1-l5-e9", type: "recognize", prompt: "Which letter makes this sound?", target: consonants.tieut, options: [consonants.kieuk, consonants.tieut, consonants.pieup, consonants.chieut, consonants.hieut], estimatedSeconds: 20 },
    { id: "m1-l5-e10", type: "recognize", prompt: "Which letter makes this sound?", target: consonants.chieut, options: [consonants.kieuk, consonants.tieut, consonants.pieup, consonants.chieut, consonants.hieut], estimatedSeconds: 20 },
    { id: "m1-l5-e11", type: "produce", prompt: "Type the sound this letter makes.", target: consonants.kieuk, estimatedSeconds: 25, note: FIRST_PRODUCE_NOTE },
    { id: "m1-l5-e12", type: "produce", prompt: "Type the sound this letter makes.", target: consonants.pieup, estimatedSeconds: 20 },
    { id: "m1-l5-e13", type: "produce", prompt: "Type the sound this letter makes.", target: consonants.hieut, estimatedSeconds: 20 },
  ],
};

export const buildEveryBlock: Lesson = {
  id: "m1-l6b",
  slug: "build-any-block",
  number: 7,
  title: "Build any block",
  blurb: "Every consonant, every basic vowel. Build any syllable you can read, then build a few from sound alone.",
  introduces: [],
  estimatedMinutes: 6,
  exercises: [
    {
      id: "m1-l6b-e1",
      type: "build",
      prompt: "Build any syllable block",
      note: "You know every basic letter now. Pick any consonant and any vowel and hear the block it makes. Remember ㅇ is silent at the start, so ㅇ plus a vowel is just the vowel: 아, 어, 오.",
      target: "",
      options: [
        consonants.giyeok,
        consonants.nieun,
        consonants.digeut,
        consonants.rieul,
        consonants.mieum,
        consonants.bieup,
        consonants.siot,
        consonants.ieung,
        consonants.jieut,
        consonants.chieut,
        consonants.kieuk,
        consonants.tieut,
        consonants.pieup,
        consonants.hieut,
        vowels.a,
        vowels.eo,
        vowels.o,
        vowels.u,
        vowels.eu,
        vowels.i,
      ],
      estimatedSeconds: 60,
    },
    {
      id: "m1-l6b-e2",
      type: "buildListen",
      prompt: "Build what you hear",
      note: "Now the real test: no letters on screen. Listen, recall which letters make that sound, and build the block. Tap the speaker to hear it again.",
      target: "가",
      options: [
        consonants.giyeok,
        consonants.nieun,
        consonants.digeut,
        consonants.rieul,
        consonants.mieum,
        consonants.bieup,
        consonants.siot,
        consonants.ieung,
        consonants.jieut,
        consonants.chieut,
        consonants.kieuk,
        consonants.tieut,
        consonants.pieup,
        consonants.hieut,
        vowels.a,
        vowels.eo,
        vowels.o,
        vowels.u,
        vowels.eu,
        vowels.i,
      ],
      estimatedSeconds: 30,
    },
    {
      id: "m1-l6b-e3",
      type: "buildListen",
      prompt: "Build what you hear",
      target: "노",
      options: [
        consonants.giyeok,
        consonants.nieun,
        consonants.digeut,
        consonants.rieul,
        consonants.mieum,
        consonants.bieup,
        consonants.siot,
        consonants.ieung,
        consonants.jieut,
        consonants.chieut,
        consonants.kieuk,
        consonants.tieut,
        consonants.pieup,
        consonants.hieut,
        vowels.a,
        vowels.eo,
        vowels.o,
        vowels.u,
        vowels.eu,
        vowels.i,
      ],
      estimatedSeconds: 30,
    },
    {
      id: "m1-l6b-e4",
      type: "buildListen",
      prompt: "Build what you hear",
      target: "무",
      options: [
        consonants.giyeok,
        consonants.nieun,
        consonants.digeut,
        consonants.rieul,
        consonants.mieum,
        consonants.bieup,
        consonants.siot,
        consonants.ieung,
        consonants.jieut,
        consonants.chieut,
        consonants.kieuk,
        consonants.tieut,
        consonants.pieup,
        consonants.hieut,
        vowels.a,
        vowels.eo,
        vowels.o,
        vowels.u,
        vowels.eu,
        vowels.i,
      ],
      estimatedSeconds: 30,
    },
  ],
};


export const alphabetCheckpoint: Lesson = {
  id: "m1-l8",
  slug: "alphabet-checkpoint",
  number: 8,
  title: "Alphabet checkpoint",
  blurb: "Everything mixed together: hear it, read it, build it. Proof you know the whole alphabet.",
  introduces: [],
  estimatedMinutes: 5,
  exercises: [
    {
      id: "m1-l8-e1",
      type: "recognize",
      prompt: "Which letter makes this sound?",
      note: "Everything is mixed together now. Same skills, shuffled across the whole alphabet.",
      target: consonants.bieup,
      options: [consonants.bieup, consonants.digeut, consonants.mieum, consonants.pieup],
      estimatedSeconds: 20,
    },
    {
      id: "m1-l8-e2",
      type: "recall",
      prompt: "What sound does this letter make?",
      target: vowels.eo,
      options: [vowels.eo, vowels.o, vowels.u, vowels.a],
      estimatedSeconds: 15,
    },
    {
      id: "m1-l8-e3",
      type: "buildTest",
      prompt: "Build this sound",
      target: "나",
      options: [
        consonants.giyeok, consonants.nieun, consonants.mieum, consonants.siot,
        vowels.a, vowels.eo, vowels.o, vowels.i,
      ],
      estimatedSeconds: 30,
    },
    {
      id: "m1-l8-e4",
      type: "recognize",
      prompt: "Which letter makes this sound?",
      target: vowels.yo,
      options: [vowels.yo, vowels.yu, vowels.o, vowels.u],
      estimatedSeconds: 20,
    },
    {
      id: "m1-l8-e5",
      type: "recall",
      prompt: "What sound does this letter make?",
      target: consonants.kieuk,
      options: [consonants.kieuk, consonants.tieut, consonants.pieup, consonants.hieut],
      estimatedSeconds: 15,
    },
    {
      id: "m1-l8-e6",
      type: "buildListen",
      prompt: "Build what you hear",
      target: "무",
      options: [
        consonants.giyeok, consonants.nieun, consonants.mieum, consonants.siot, consonants.bieup,
        vowels.a, vowels.o, vowels.u, vowels.eu, vowels.i,
      ],
      estimatedSeconds: 30,
    },
    {
      id: "m1-l8-e7",
      type: "recognize",
      prompt: "Which letter makes this sound?",
      target: consonants.jieut,
      options: [consonants.jieut, consonants.chieut, consonants.siot, consonants.digeut],
      estimatedSeconds: 20,
    },
    {
      id: "m1-l8-e8",
      type: "buildTest",
      prompt: "Build this sound",
      target: "도",
      options: [
        consonants.digeut, consonants.rieul, consonants.siot, consonants.giyeok,
        vowels.o, vowels.u, vowels.a, vowels.eo,
      ],
      estimatedSeconds: 30,
    },
    {
      id: "m1-l8-e9",
      type: "recall",
      prompt: "What sound does this letter make?",
      target: consonants.hieut,
      options: [consonants.hieut, consonants.kieuk, consonants.pieup, consonants.chieut],
      estimatedSeconds: 15,
    },
    {
      id: "m1-l8-e10",
      type: "buildListen",
      prompt: "Build what you hear",
      target: "기",
      options: [
        consonants.giyeok, consonants.nieun, consonants.siot, consonants.mieum,
        vowels.i, vowels.a, vowels.o, vowels.u,
      ],
      estimatedSeconds: 30,
    },
  ],
};
