import type { Vowel } from "../types";

export const vowels: Record<string, Vowel> = {
  a: {
    kind: "vowel",
    char: "ㅏ",
    romanization: "a",
    ipa: "/a/",
    orientation: "vertical",
    mnemonicHook: "father",
    mnemonicShape: "A vertical line with a small dash pointing right.",
    articulation: "Mouth open and relaxed, tongue low. Like the ah you say at the doctor.",
    soundsLike: { word: "father", phonetic: "ah" },
    audioHint: "아",
  },
  eo: {
    kind: "vowel",
    char: "ㅓ",
    romanization: "eo",
    ipa: "/ʌ/",
    orientation: "vertical",
    mnemonicHook: "son",
    mnemonicShape: "A vertical line with a small dash pointing left.",
    articulation: "Mouth open, tongue pulled back. Like the u in sun.",
    soundsLike: { word: "son", phonetic: "uh" },
    audioHint: "어",
  },
  o: {
    kind: "vowel",
    char: "ㅗ",
    romanization: "o",
    ipa: "/o/",
    orientation: "horizontal",
    mnemonicHook: "old",
    mnemonicShape: "A horizontal line with a small dash pointing up.",
    articulation: "Lips rounded and tight. Like the o in old.",
    soundsLike: { word: "old", phonetic: "oh" },
    audioHint: "오",
  },
  u: {
    kind: "vowel",
    char: "ㅜ",
    romanization: "u",
    ipa: "/u/",
    orientation: "horizontal",
    mnemonicHook: "new",
    mnemonicShape: "A horizontal line with a small dash pointing down.",
    articulation: "Lips tightly rounded, like blowing through a straw. Like the oo in new.",
    soundsLike: { word: "new", phonetic: "oo" },
    audioHint: "우",
  },
  eu: {
    kind: "vowel",
    char: "ㅡ",
    romanization: "eu",
    ipa: "/ɯ/",
    orientation: "horizontal",
    mnemonicHook: "ugh",
    mnemonicShape: "A single horizontal line, like the bar above a dash.",
    articulation: "Lips spread flat like a smile, tongue pulled back. Like the ugh you say when something is gross.",
    soundsLike: { word: "ugh", phonetic: "eu" },
    audioHint: "으",
  },
  i: {
    kind: "vowel",
    char: "ㅣ",
    romanization: "i",
    ipa: "/i/",
    orientation: "vertical",
    mnemonicHook: "see",
    mnemonicShape: "A single tall vertical line, like the English letter I.",
    articulation: "Lips spread wide, tongue forward and high. Like the ee in see.",
    soundsLike: { word: "see", phonetic: "ee" },
    audioHint: "이",
  },
  ya: {
    kind: "vowel",
    char: "ㅑ",
    romanization: "ya",
    ipa: "/ja/",
    orientation: "vertical",
    mnemonicHook: "yard",
    mnemonicShape: "Like ㅏ but with two dashes pointing right. The extra dash adds a y sound.",
    articulation: "Start with a y sound, then open into ah. Like the ya in yard.",
    soundsLike: { word: "yard", phonetic: "ya" },
    audioHint: "야",
  },
  yeo: {
    kind: "vowel",
    char: "ㅕ",
    romanization: "yeo",
    ipa: "/jʌ/",
    orientation: "vertical",
    mnemonicHook: "young",
    mnemonicShape: "Like ㅓ but with two dashes pointing left. The extra dash adds a y sound.",
    articulation: "Start with a y sound, then into uh. Like the you in young.",
    soundsLike: { word: "young", phonetic: "yuh" },
    audioHint: "여",
  },
  yo: {
    kind: "vowel",
    char: "ㅛ",
    romanization: "yo",
    ipa: "/jo/",
    orientation: "horizontal",
    mnemonicHook: "yoga",
    mnemonicShape: "Like ㅗ but with two dashes pointing up. The extra dash adds a y sound.",
    articulation: "Start with a y sound, then into oh. Like the yo in yoga.",
    soundsLike: { word: "yoga", phonetic: "yo" },
    audioHint: "요",
  },
  yu: {
    kind: "vowel",
    char: "ㅠ",
    romanization: "yu",
    ipa: "/ju/",
    orientation: "horizontal",
    mnemonicHook: "you",
    mnemonicShape: "Like ㅜ but with two dashes pointing down. The extra dash adds a y sound.",
    articulation: "Start with a y sound, then into oo. Like the word you.",
    soundsLike: { word: "you", phonetic: "yoo" },
    audioHint: "유",
  },
};
